

const WEBSITE_NAME = "TECHEASE";
const DOMAIN_NAME = "localhost:7000";
const DOMAIN_URL = "http://localhost:7000"

const VENDOR_TYPE = {
    ADMIN: "ADMIN",
    SUB_ADMIN: "SUB_ADMIN",
}

const MIN_STOCK = 10;
const FIRST_ORDER_COUEPN_OFFER=10

const ORDER_STATUS = {
    ORDER_RECEIVED: "ORDER RECEIVED",
    PREPARING_ORDER: "PREPARING YOUR ORDER",
    READY_FOR_PICKUP: "ORDER READY FOR PICKUP",
    PICKED: "PICKED",
    DELIVERED: "DELIVERED",
    CANCELED: "CANCELLED",
    RETURNED: "RETURNED",
    RETURNED_REQUEST: "RETURNED REQUEST",
    REFUND: "REFUND"
    // PENDING: "PENDING",
    // PROCESSING: "PROCESSING",
    // SHIPPED: "SHIPPED",
    // CANCEL_REQUEST: "CANCEL_REQUEST",
    // CANCELED: "CANCELLED",
    // RETURNED: "RETURNED",
    // RETURNED_REQUEST: "RETURNED_REQUEST",
    // REFUND: "REFUND",
    // ONHOLD: "ONHOLD",
    // DELIVERED: "DELIVERED",
}

const OTP_TYPE = {
    UPDATE_PHONE: "UPDATE_PHONE"
}


const TWILIO_CONFIG = {
    accountSid: "ACbca57e55268f1a62cfdf1756573b5e64",
    authToken: "3b2c6f31b39edcfe3d49b8005e1c53a6"
}
    
const INVOICE_STATUS = {
    PENDING: "PENDING",
    PAID: "PAID",
    UNPAID: "UNPAID",
    PARTIAL: "PARTIAL",
    OVERDUE: "OVERDUE",
    REFUNDED: "REFUNDED",
    WITHdraw: "withdraw",
};


const PRODUCT_OPTION = {
    FRESH_VEGETABLES: 'FRESH VEGETABLES',
    FRESH_FRUITS: 'FRESH FRUITS',
    MEAL_KITS: 'MEAL KITS',
    ORGANIC_PRODUCTS: 'ORGANIC PRODUCTS',
    SALADS: 'SALADS',
    SMOOTHIES: 'SMOOTHIES',
    HEALTHY_SNACKS: 'HEALTHY SNACKS',
    READY_TO_COOK: 'READY-TO-COOK MEALS',
    JUICES: 'JUICES',
    FARM_TO_TABLE: 'FARM-TO-TABLE PRODUCE',
    EXOTIC_FRUITS: 'EXOTIC FRUITS',
    GOURMET_MEALS: 'GOURMET MEALS',
    GLUTEN_FREE: 'GLUTEN-FREE OPTIONS',
    VEGAN_CHOICES: 'VEGAN SELECTIONS',
};


const RAZORPAY_CRED = {
    KEY: "rzp_test_pNwP40SbPGEBq5",
    SECRET: "I2Gef5UldOntfIHZv8wWoKLZ"
}

const WALLET_CREDIT_FROM = {
    ADMIN_SIDE: "ADMIN_SIDE",
    SIGN_UP: "SIGN_UP",
    REFUND: "REFUND",
    REFER: "REFER"
}

const CHART_TYPE= {
    "YEARLY": "YEARLY",
    "MONTHLY": "MONTHLY",
    "DAILY": "DAILY"
}




const PAYMENT_METHOD = {
    RAZORPAY: "Razorpay",
    COD: "CASH ON DELIVERY",
    WALLET: "Wallet",
    SUPER_COIN: "SUPER COIN"
}

const PRODUCT_VARIATION = {
    "2kg": 2.00,
    "1kg": 1.00,
    "500gm": 0.50,
    "250gm": 0.25,
};

function GET_KEY_BY_VALUE(object = PRODUCT_VARIATION, value) {
    return Object.keys(object).find((eachItems) => object[eachItems] == value) ?? value;
}

module.exports = {
    WEBSITE_NAME,
    DOMAIN_NAME,
    VENDOR_TYPE,
    ORDER_STATUS,
    MIN_STOCK,
    INVOICE_STATUS,
    PAYMENT_METHOD,
    PRODUCT_OPTION,
    TWILIO_CONFIG,
    RAZORPAY_CRED,
    PRODUCT_VARIATION,
    GET_KEY_BY_VALUE,
    DOMAIN_URL,
    OTP_TYPE,
    WALLET_CREDIT_FROM,
    CHART_TYPE,
    FIRST_ORDER_COUEPN_OFFER
}